// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQq_jbisA_y00_hIT-671sEs-_qSdDFn0',
    appId: '1:963697554313:web:0e0f100e9dba9a0573a758',
    messagingSenderId: '963697554313',
    projectId: 'fireauth-test-d4e02',
    authDomain: 'fireauth-test-d4e02.firebaseapp.com',
    storageBucket: 'fireauth-test-d4e02.appspot.com',
    measurementId: 'G-65XNJDYW0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgMH4J2NO5DR6obMWdvXF5AW23ziaFdrE',
    appId: '1:963697554313:android:7e62e24795f5f42473a758',
    messagingSenderId: '963697554313',
    projectId: 'fireauth-test-d4e02',
    storageBucket: 'fireauth-test-d4e02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM-Cax-xPIv7Z83f_GGPH1a2uJXmr4czE',
    appId: '1:963697554313:ios:3fb017398e43552773a758',
    messagingSenderId: '963697554313',
    projectId: 'fireauth-test-d4e02',
    storageBucket: 'fireauth-test-d4e02.appspot.com',
    iosBundleId: 'com.example.fireauthtestapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM-Cax-xPIv7Z83f_GGPH1a2uJXmr4czE',
    appId: '1:963697554313:ios:3fb017398e43552773a758',
    messagingSenderId: '963697554313',
    projectId: 'fireauth-test-d4e02',
    storageBucket: 'fireauth-test-d4e02.appspot.com',
    iosBundleId: 'com.example.fireauthtestapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQq_jbisA_y00_hIT-671sEs-_qSdDFn0',
    appId: '1:963697554313:web:ce76c94af87e9a7973a758',
    messagingSenderId: '963697554313',
    projectId: 'fireauth-test-d4e02',
    authDomain: 'fireauth-test-d4e02.firebaseapp.com',
    storageBucket: 'fireauth-test-d4e02.appspot.com',
    measurementId: 'G-TNWT7BQQ1N',
  );
}
