// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ5wYzvnJ6n2IgRmMBNDiU6Qy9VsHBeyc',
    appId: '1:402883918687:web:a23b6412c692b822d614ea',
    messagingSenderId: '402883918687',
    projectId: 'firekaijuu',
    authDomain: 'firekaijuu.firebaseapp.com',
    storageBucket: 'firekaijuu.appspot.com',
    measurementId: 'G-D5R2FR87XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdrd6DchjQjRm_f7IqEv02PqJDIW6DMSU',
    appId: '1:402883918687:android:2f72137401e47752d614ea',
    messagingSenderId: '402883918687',
    projectId: 'firekaijuu',
    storageBucket: 'firekaijuu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUvtpMqPVgrkerGfrF8pDmTPaqUiQdjSk',
    appId: '1:402883918687:ios:6802f76042e3475cd614ea',
    messagingSenderId: '402883918687',
    projectId: 'firekaijuu',
    storageBucket: 'firekaijuu.appspot.com',
    iosBundleId: 'com.example.kaijuuV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUvtpMqPVgrkerGfrF8pDmTPaqUiQdjSk',
    appId: '1:402883918687:ios:6802f76042e3475cd614ea',
    messagingSenderId: '402883918687',
    projectId: 'firekaijuu',
    storageBucket: 'firekaijuu.appspot.com',
    iosBundleId: 'com.example.kaijuuV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ5wYzvnJ6n2IgRmMBNDiU6Qy9VsHBeyc',
    appId: '1:402883918687:web:5c46ac69ea7356c3d614ea',
    messagingSenderId: '402883918687',
    projectId: 'firekaijuu',
    authDomain: 'firekaijuu.firebaseapp.com',
    storageBucket: 'firekaijuu.appspot.com',
    measurementId: 'G-2LTDV428FR',
  );

}