// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy8dpAQDYaX4rH7rLgdvj1cNPeoEQUHS4',
    appId: '1:642909963399:web:54a83f985aa4f9a8f26422',
    messagingSenderId: '642909963399',
    projectId: 'pomokaijuu',
    authDomain: 'pomokaijuu.firebaseapp.com',
    storageBucket: 'pomokaijuu.appspot.com',
    measurementId: 'G-2MRDE8V7ZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFmnbkDm_sMhcTTt-hDt1l6y9sycmyAno',
    appId: '1:642909963399:android:98b4c0cdcc205257f26422',
    messagingSenderId: '642909963399',
    projectId: 'pomokaijuu',
    storageBucket: 'pomokaijuu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqQqZsN6zNqmkGfWsewoI2ynizPjOsjSQ',
    appId: '1:642909963399:ios:afdaf0f64d779343f26422',
    messagingSenderId: '642909963399',
    projectId: 'pomokaijuu',
    storageBucket: 'pomokaijuu.appspot.com',
    iosBundleId: 'com.example.kaijuuV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqQqZsN6zNqmkGfWsewoI2ynizPjOsjSQ',
    appId: '1:642909963399:ios:b6e4954916bbd357f26422',
    messagingSenderId: '642909963399',
    projectId: 'pomokaijuu',
    storageBucket: 'pomokaijuu.appspot.com',
    iosBundleId: 'com.example.kaijuuV1.RunnerTests',
  );
}
